<section id="team" class="team lite no-padding-bottom">
	<div class="container">
		        <div class="row">
			<div class="col-md-12">			
				<h2 class="smalltitle">Our Team<span></span></h2>
			</div>
        </div>
                        <div class="row multi-columns-row">
            <div class="col-sm-4 col-md-4 col-lg-4 member"><div class="hovereffect img-circle center-block"><img src="/content/about/about-pic.jpg" alt="Hans Desjarlais" class="img-responsive"></div><h3 class="t-name">Hans Desjarlais</h3><div class="t-type">Project Manager</div><ul class="socials"><li><a class="facebook" target="_blank" href="#"><i class="fa fa-facebook fa-lg"></i></a></li><li><a class="twitter" target="_blank" href="#"><i class="fa fa-twitter fa-lg"></i></a></li><li><a class="google" target="_blank" href="#"><i class="fa fa-google-plus fa-lg"></i></a></li><li><a class="github" target="_blank" href="#"><i class="fa fa-github fa-lg"></i></a></li><li><a class="behance" target="_blank" href="#"><i class="fa fa-behance fa-lg"></i></a></li><li><a class="linkedin" target="_blank" href="#"><i class="fa fa-linkedin fa-lg"></i></a></li><li><a class="instagram" target="_blank" href="#"><i class="fa fa-instagram fa-lg"></i></a></li></ul><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</div><div class="col-sm-4 col-md-4 col-lg-4 member"><div class="hovereffect img-circle center-block"><img src="/content/about/about-pic2.jpg" alt="Janelle Brandon" class="img-responsive"></div><h3 class="t-name">Janelle Brandon</h3><div class="t-type">Graphic Designer</div><ul class="socials"><li><a class="facebook" target="_blank" href="#"><i class="fa fa-facebook fa-lg"></i></a></li><li><a class="twitter" target="_blank" href="#"><i class="fa fa-twitter fa-lg"></i></a></li><li><a class="google" target="_blank" href="#"><i class="fa fa-google-plus fa-lg"></i></a></li><li><a class="github" target="_blank" href="#"><i class="fa fa-github fa-lg"></i></a></li><li><a class="behance" target="_blank" href="#"><i class="fa fa-behance fa-lg"></i></a></li><li><a class="linkedin" target="_blank" href="#"><i class="fa fa-linkedin fa-lg"></i></a></li><li><a class="instagram" target="_blank" href="#"><i class="fa fa-instagram fa-lg"></i></a></li></ul><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</div><div class="col-sm-4 col-md-4 col-lg-4 member"><div class="hovereffect img-circle center-block"><img src="/content/about/about-pic3.jpg" alt="Eric Kelly" class="img-responsive"></div><h3 class="t-name">Eric Kelly</h3><div class="t-type">Senior Programmer</div><ul class="socials"><li><a class="facebook" target="_blank" href="#"><i class="fa fa-facebook fa-lg"></i></a></li><li><a class="twitter" target="_blank" href="#"><i class="fa fa-twitter fa-lg"></i></a></li><li><a class="google" target="_blank" href="#"><i class="fa fa-google-plus fa-lg"></i></a></li><li><a class="github" target="_blank" href="#"><i class="fa fa-github fa-lg"></i></a></li><li><a class="behance" target="_blank" href="#"><i class="fa fa-behance fa-lg"></i></a></li><li><a class="linkedin" target="_blank" href="#"><i class="fa fa-linkedin fa-lg"></i></a></li><li><a class="instagram" target="_blank" href="#"><i class="fa fa-instagram fa-lg"></i></a></li></ul><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</div>		</div>
        	</div>
</section><!--team-->